# Generated by Django 3.0.3 on 2020-04-09 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200404_1803'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelReservation',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('rooms', models.CharField(blank=True, editable=False, max_length=50)),
                ('initial_amount', models.PositiveSmallIntegerField(blank=True, editable=False)),
                ('cancel_in_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_edited_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Reservation')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
