# Generated by Django 3.0.3 on 2020-03-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200318_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['first_name', 'middle_name', 'last_name'], 'permissions': (('can_view_customer', 'Can view customer'),)},
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_of_rooms',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='Max_no_of_guest',
            field=models.PositiveSmallIntegerField(default=True),
        ),
    ]
