# Generated by Django 3.0.3 on 2020-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_roomtype_no_of_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_proof',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
