# Generated by Django 3.0.3 on 2020-04-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200404_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_proof',
            field=models.ImageField(upload_to=''),
        ),
    ]
